version: '3.7'

services:
  wordpress:
    container_name: wp-web
    links:
      - db
    image: wordpress:latest
    ports:
      - "8083:80"
    volumes:
      - ./html:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: database_password
    depends_on:
      - db

  db:
    container_name: wp-db
    image: mariadb:10.4
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33060:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: database_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: database_password

volumes:
    db_data: